#!/bin/bash

ghdl -a graphics.vhdl &&\
    ghdl -e graphics &&\
    ghdl -a pong_top.vhdl &&\
    ghdl -e pongtop &&\
    ghdl -a pong_toptb.vhdl &&\
    ghdl -e pongtoptb &&\
    ghdl -r pongtoptb --wave=wave.ghw
